apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: bulk               # plugin name must match your manifest file name (e.g. foo.yaml)
spec:
  version: "v1.1.0-beta"       # optional, only for documentation purposes
  platforms:
  # specify installation script for linux and darwin (macOS)
  - selector:             # a regular Kubernetes selector
      matchLabels:
        os: linux
    # url for downloading the package archive:
    uri: https://github.com/emreodabas/kubectl-plugins/archive/1.1.0-beta.tar.gz
    # sha256sum of the file downloaded above:
    sha256: "c2ceaf19be1389ed55433729b40c40abbb45204bcdc975e556bfc50394fd25bb"
    files:                     # copy the used files out of the zip archive
    - from: kubectl-plugins-1.1.0-beta/kubectl-bulk # path to the files extracted from archive
      to: "."               # '.' refers to the root of plugin install directory
    bin: ./kubectl-bulk  # path to the plugin executable after copying files above
  shortDescription: Prints the environment variables.
  # (optional) use caveats field to show post-installation recommendations
  caveats: |
    This plugin needs the following programs:
    * grep
    * sed
  description: |
    This plugin useful for Bulk operations.
    You can easily do bulk operations on all resource types like deployments, services, pods etc.
    Bulk plugin has two part, first you select resources with bulk command, then chose your command 
    (get|list|create|update|delete|remove|rollout) with parameters.      
          <!-- https://github.com/emreodabas/kubectl-plugins -->