apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: interactive               
spec:
  version: "v1.1.0-beta"      
  platforms:
  - selector:             
      matchLabels:
        os: linux
    uri: https://github.com/emreodabas/kubectl-plugins/archive/v1.1.0-beta.tar.gz
    sha256: "80f7b55d82673253eb0957d2c248163fcce3e4c3bc609410b1e9ee2d6d6a91a7"
    files:                     
    - from: kubectl-plugins-1.1.0-beta/kubectl-it 
      to: "."               
    bin: ./kubectl-interactive  
  shortDescription: Prints the environment variables.
  caveats: |
    This plugin needs the following programs:
    * fzf
  description: |
   kubectl interactive execute exec, edit, delete and log commands with interactive selection.
          <!-- https://github.com/emreodabas/kubectl-plugins -->