apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: it               # plugin name must match your manifest file name (e.g. foo.yaml)
spec:
  version: "v1.1.0-beta"       # optional, only for documentation purposes
  platforms:
  # specify installation script for linux and darwin (macOS)
  - selector:             # a regular Kubernetes selector
      matchLabels:
        os: linux
    # url for downloading the package archive:
    uri: https://github.com/emreodabas/kubectl-plugins/archive/1.1.0-beta.tar.gz
    # sha256sum of the file downloaded above:
    sha256: "c2ceaf19be1389ed55433729b40c40abbb45204bcdc975e556bfc50394fd25bb"
    files:                     # copy the used files out of the zip archive
    - from: kubectl-plugins-1.1.0-beta/kubectl-it # path to the files extracted from archive
      to: "."               # '.' refers to the root of plugin install directory
    bin: ./kubectl-it  # path to the plugin executable after copying files above
  shortDescription: Prints the environment variables.
  # (optional) use caveats field to show post-installation recommendations
  caveats: |
    This plugin needs the following programs:
    * fzf
  description: |
   kubectl it execute exec, edit, delete and log commands with interactive selection.
          <!-- https://github.com/emreodabas/kubectl-plugins -->